### ISSUE TITLE
Love your tutorial - but seeing an error

### ISSUE THREAD

**Issue by sparkling** [Dawntraoz/full-static-nuxt-storyblok#243]
Hi Dawn,

thank you so much for creating this tutorial, it has saved me a ton of time. I did the following:
1. Cloned the repo
2. Create a new space in Storyblok, added all the content from your README
3. added a ".env" file with API_KEY=**** from: Storyblok -> my space -> Settings -> Access Token -> Preview
4. yarn install
5. yarn dev

In the web console, I see this error message:

<img width="1784" alt="Screenshot 2022-02-23 at 16 02 56" src="https://user-images.githubusercontent.com/311648/155357930-17ad10ee-7b3e-49ee-9edd-7734cbc6d852.png">

It's also not displaying any content from Storyblok:

<img width="1312" alt="Screenshot 2022-02-23 at 16 08 33" src="https://user-images.githubusercontent.com/311648/155358952-3eb83a9e-dd2d-4506-93ac-453c7f68883b.png">

Any hints you could give would be greatly appreciated. 

Thanks!

Henrik

**Comment by sparkling** [comment]
had the wrong name for the page-template, renamed to page-template

**Comment by Dawntraoz** [comment]
@sparkling happy to hear it was just a naming issue 😍 

Anyway, whatever you need, I'm here and on [Twitter](https://twitter.com/dawntraoz) I have the DMs open 🤗
